olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/Provenance.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/ProvenanceUtil.java
pom.xml

The toString on a provenance can be tricky to read, but is very compact. This PR adds a few more options:
- one which converts the provenance into a String that's got newlines, tabs and spaces in it to delimit the different fields.
- one which converts the provenance into a structure of immutable Maps, Lists and Strings, representing the full toString information.
This latter form is suitable for easily converting into readable JSON.

Provenance transforms

---

README-Configuration.md
THIRD_PARTY_LICENSES.txt
docs/Internals.md
docs/Security.md
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/command/CommandGroup.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurableMXBean.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/util/StopWatch.java
pom.xml

Bump the dev version, add a couple of reporting plugins to the pom file, fix some javadoc issues and add some more markdown docs for the internals and security considerations.

Bumping the development version to 5.1.5-SNAPSHOT

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/command/CommandInterpreter.java

If a CommandInterpreter defines a default command, then when the CI is exiting, as part of it's cleanup it runs the "on_exit" command. If no on_exit command is defined, then the default command was inadvertently run at close time. This can very easily lead to exceptions being reported during the close process.
Fix is just to check if the unknown command is "on_exit" before running the default command.

CommandInterpreter runs the default command when exiting, which can lead to exceptions

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/Options.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/OptionsTest.java

Added a little extra error checking when we fail to instantiate an Options class to account for access errors with the constructor or the class as well as if the constructor is missing so that we can give a more accurate error message. Added tests to check behavior.

Give clearer errors when there are access problems with Options classes

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/ProvenanceUtil.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/impl/NullConfiguredProvenance.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/provenance/ExampleProvenancableConfigurable.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/provenance/ProvenanceUtilTest.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/provenance/TestProvenancableConfigurable.java

ConfigurationData isn't supposed to have any null fields, and automatically extracting provenance from an object with null fields inserts `NullConfiguredProvenance` to ensure that it records all the (provenancable) fields. This PR links up the two bits to ensure that converting a provenance into a configuration gives a valid configuration. Previously the NullConfiguredProvenance would show up as an empty reference to a configurable type, which works if the configurable type is a class (without mandatory fields) but fails if the field type is an interface as the interface isn't constructable.

Fixing ProvenanceUtil.extractConfiguration so NullConfiguredProvnances don't leak into ConfigurationData

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationManager.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/GenericConfigTest.java

This adds `public Map<String,T> lookupAllMap(Class<T> clazz)` to `ConfigurationManager`. It has the same behaviour as `lookupAll` except it returns a Map where the keys are the configurable object names, and the values are the corresponding objects.
We could consider refactoring `lookupAll` and `lookupAllMap` so they use the same code, and have `lookupAll` wrap the values from `lookupAllMap` in an `ArrayList`, but I've not yet done that.

Adding a lookupAllMap method

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/DescribeConfigurable.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/Options.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/OptionsTest.java

Enums currently display the enum constants in any usage string, and in `DescribeConfigurable` both enum and EnumSet fields display the enum constants. This PR fixes the usage string generation so that it displays the enum constants for EnumSet option fields. I also added Javadoc to the rest of the methods in `Options`.

Adding the enum constants to the type displayed for an EnumSet Option in the usage String

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/property/GlobalProperties.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/property/ImmutableGlobalProperties.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/GlobalPropertyTest.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/property/GlobalPropertiesTest.java

The GlobalProperties class throws an exception when importing system properties if they don't map to the global property regex. Properties which don't fit this regex can't be used as global properties for replacing things so shouldn't be in there anyway. This patch fixes that, adds more javadoc to the surrounding classes, and adds a test for the behaviour.

Fix for importing system properties into GlobalProperties

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/DescribeConfigurable.java

This makes it easier to use the chunks of `DescribeConfigurable` in jshell (or a jupyter notebook). We do this in [Tribuo's tutorials](https://tribuo.org/learn/4.0/tutorials/configuration-tribuo-v4.html#How-does-configuration-work?) to explain how the config system works and it's nice to be able to do it when exploring a new configurable class for the first time.

Making DescribeConfigurable.FieldInfo public as it's returned by public methods

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationManager.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/ImportConfigTest.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/ListConfig.java

`ConfigurationManager.importConfigurable` throws when it inspects an object with a null valued configurable field. `null` fields are fine if the `@Config` annotation does not have `mandatory = true`, and this patch updates the import logic to allow that, along with adding a specific exception thrown if a mandatory field is null. It also adds a test for this behaviour.

Fix for importing configurables with null fields

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationManager.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/util/MutableNumber.java

There's a bug in Tribuo's multidimensional regression because it assumed `MutableNumber.copyMap` was preserving iteration order. There are a number of fixes for Tribuo coming as this issue exposed several places where the proper validation wasn't being applied, but this PR modifies `copyMap` so it preserves iteration order.

Fixing MutableNumber.copyMap so it preserves iteration order

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationManager.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/FieldType.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/PropertySheet.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/impl/SkeletalConfiguredObjectProvenance.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/AllFieldsConfigurable.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/AllFieldsConfiguredTest.java
olcut-core/src/test/resources/com/oracle/labs/mlrg/olcut/config/allConfig.xml

Not sure why it wasn't there already, but this rounds out OLCUT's coverage of Java primitives to include all single dimensional primitive arrays.
I added it to the `AllFieldsConfigurable` and extended the tests based on it rather than add a new test specifically for boolean arrays.

Adds support for configurable and provenancable boolean arrays

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/command/CommandInterpreter.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/command/StandardCommandTest.java

This PR adds a command to the standard set of commands available in the command shell that allows you to modify the log level either for a specific target logger or for the log handlers. I've also added a stub of a unit test for the standard commands that currently only tests the log level command. If any standard commands are touched, we should add tests for them as we go.

Adds command to modify the log level from the command shell

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationManager.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/DescribeConfigurable.java

This was accidentally removed when we turned off the config file option for `DescribeConfigurable`. I've added back the `--config-file-formats` option though it goes through a slightly different codepath.
I also javadoc'd the class on the way through.

Adding file format support to DescribeConfigurable

---

olcut-config-json/src/main/java/com/oracle/labs/mlrg/olcut/config/json/JsonProvenanceMarshaller.java
olcut-config-json/src/main/java/com/oracle/labs/mlrg/olcut/config/json/JsonProvenanceSerialization.java
olcut-config-json/src/test/java/com/oracle/labs/mlrg/olcut/config/json/JsonProvenanceConversionTest.java
olcut-config-json/src/test/java/com/oracle/labs/mlrg/olcut/config/json/JsonProvenanceSerializationTest.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/io/FlatMarshalledProvenance.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/io/ListMarshalledProvenance.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/io/MapMarshalledProvenance.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/io/MarshalledProvenance.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/io/ObjectMarshalledProvenance.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/io/ProvenanceMarshaller.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/io/ProvenanceSerialization.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/io/SimpleMarshalledProvenance.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/io/XMLProvenanceMarshaller.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/io/XMLProvenanceSerialization.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/provenance/XmlProvenanceConversionTest.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/provenance/XmlProvenanceSerializationTest.java

Tribuo needs a plain text minimal dependency string serialization format for provenance to allow storage in ONNX model protobufs which only expose String metadata fields. This PR adds an XML serialization format for provenance. It's not particularly pretty, but it does work and is relatively minimal as XML goes.
I also added an interface for Provenance marshalling which the XML serializer implements and I added a wrapper class for the Json provenance serializer to simplify the use of that class (which previously required registering things with the Jackson `ObjectMapper`).
Once this PR is merged I'll update the protobuf provenance serialization class so it implements `ProvenanceMarshaller` and put in a PR for that too.

Adds XML serialization and deserialization support for MarshalledProvenances

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/ProvenanceUtil.java

The ordering of the provenance objects isn't directly visible when working with them and converting them into configuration data. We need to be able to see the provenance objects and line them up with the corresponding configuration data, so we know what configuration name the corresponding provenance object has.
This PR splits up `extractConfiguration` into two methods which allow users who need the ordering information (principally Tribuo's reproducibility system) to see it, while being fairly safe as the constructor for the carrier object is package private.

Split extractConfiguration(ObjectProvenance) into two methods

---

.github/workflows/maven-macos.yml
.github/workflows/maven-ubuntu.yml
.github/workflows/maven-windows.yml
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/ConfigurationDataTest.java
olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/util/StreamUtilTest.java

Adds Windows & macOS CIs via Github Actions. Fixes the test issue in ConfigurationData.structuralEquals by roundtripping it through instantiation once. This negates some of the benefit of the test (as it normalizes URLs, booleans and floating point values), but Windows roots paths at `C:\` and posix roots them at `\`, and those are definitely not something which we should consider equal.

Fix for ConfigurationData.structuralEquals tests on Windows

---

pom.xml

Jackson 2.12 has a stack overflow issue in it's deserializer, and I bumped the rest of the versions to latest as well.

Bumping to the latest versions of jackson, jline3, junit and protobuf

---

THIRD_PARTY_LICENSES.txt
pom.xml

Split databind out to its own version to fix an issue in just jackson-databind, but we should be very careful to make sure these line up.

Bumping databind to a version without security issues

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/util/SubprocessConnection.java
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/util/SubprocessConnectionListener.java

This branch adds SubprocessConnection, a simple wrapper that can start a process (e.g. a script interpreter for code not available on the JVM) and communicate with it by sending simple commands to its stdin and reading output from stdout via a simple contract.  That description has a lot of "simples" in it, but this is meant to make using a subprocess easy.

Added utility to easily start a subprocess and communicate with it over stdio

---

olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/provenance/ProvenanceUtil.java

There shouldn't be nulls there anyway, but now the conversion methods won't go bang.

Fixing a NPE in ProvenanceUtil

---

THIRD_PARTY_LICENSES.txt
olcut-config-edn/pom.xml
olcut-config-protobuf/pom.xml
olcut-core/pom.xml
olcut-extras/pom.xml
pom.xml

Bumping version numbers in anticipation of making a release.

Bumping version numbers for dependencies

---

.github/workflows/ISSUE_TEMPLATE/bug_report.md
.github/workflows/ISSUE_TEMPLATE/feature_request.md
.github/workflows/maven-macos.yml
.github/workflows/maven-ubuntu.yml
.github/workflows/maven-windows.yml
.github/workflows/pull_request_template.md

Adds simple issue & PR templates, and updates the CI so it doesn't point at the deleted `develop` branch.

Updating Github templates and CI

---

olcut-config-json/src/main/java/com/oracle/labs/mlrg/olcut/config/json/JsonLoader.java
olcut-config-json/src/test/java/com/oracle/labs/mlrg/olcut/config/json/test/OverrideTest.java
olcut-config-json/src/test/resources/com/oracle/labs/mlrg/olcut/config/json/test/overrideIncorrect.json
olcut-config-protobuf/src/main/java/com/oracle/labs/mlrg/olcut/config/protobuf/ProtoLoader.java
olcut-config-protobuf/src/test/java/com/oracle/labs/mlrg/olcut/config/protobuf/test/OverrideTest.java
olcut-config-protobuf/src/test/resources/com/oracle/labs/mlrg/olcut/config/protobuf/test/overrideIncorrect.pbtxt
olcut-core-test/src/test/java/com/oracle/labs/mlrg/olcut/test/config_tests/OverrideTest.java
olcut-core-test/src/test/resources/com/oracle/labs/mlrg/olcut/test/config_tests/overrideIncorrect.xml
olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/xml/SAXLoader.java

@JackSullivan found an issue where OLCUT throws an NPE in xml, json and pb when a component is inheriting its properties, but the component it inherits from isn't present in the file. Config files which exhibit this issue are invalid, but the NPE doesn't tell you what happened. This patch changes it so it throws `ConfigLoaderException` with a useful error message.

Fixing an NPE when the component is missing its parent
